---
version: "3"
services:
  db:
    build:
      context: .
      args:
        - PCIO_DB_NAME=postcodesiodb
    environment:
      - POSTGRES_DB=postcodesio
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postcodesio
    ports:
      - "5432:5432"
